### PR TITLE
SOAP TCP/Grizzly 2.4.4 migration

### PR DESCRIPTION
**Pull request by senivam**
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

### CODE REVIEW

**Comment by smillidge** [comment]
What's the context of this PR? What is the issue or feature it is resolving?

**Comment by lukasj** [comment]
Grizzly 1.0.40 is bit outdated and not maintained anymore. Better to uptake fresh, EF provided version

**Comment by lukasj** [comment]
@senivam can you rebase this on master and do 'mvn -U -C clean install -Poss-release,staging' on JDK 11, please? It should include bunch of tests now...

**Comment by senivam** [comment]
using 
```mvn -U -C clean install -Pstaging```
on JDK 11 it passes all OK. 
However profile ```oss-release``` is supposed for release only purposes. So, I've excluded it (otherwise it requires GPG sign which will always fail locally)

**Review by lukasj — APPROVED** [review]
LGTM

**Pull request merged**
